# 2048 CI/CD Pipeline - Pranav
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/2048-game:latest

  build:
    commands:
      - echo Building Docker image...
      - docker build -t 2048-game .
      - docker tag 2048-game:latest $IMAGE_URI

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $IMAGE_URI
      - printf '[{"name":"2048-container","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json